In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

from experiments import label_encoder_gender, onehot_encoder_geo, X_train, X_test, y_train

from app import geo_encoded_df, scaler

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [9]:
# one-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
# combine onehot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [11]:
# split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [16]:
## Split the data in training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
# Save the encoders and the scaler for later use
with open('label_encoder_gender_reg.pkl', 'wb') as f:
 pickle.dump(label_encoder_gender, f)

with open('onehot_encoder_geo_reg.pkl', 'wb') as f:
   pickle.dump(onehot_encoder_geo, f)

with open('scaler_reg.pkl', 'wb') as f:
  pickle.dump(scaler, f)

## ## ANN Implementation

In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [19]:
## build our ANN
model = Sequential(
    [
        Dense(64, activation = 'relu', input_shape=(X_train.shape[1],)), ## HL1 Connected with input layer
        Dense(32, activation = 'relu'), ## HL2
        Dense(1) ## output layer
    ]
)

## compile the model
model.compile(optimizer = 'adam', loss = 'mean_absolute_error', metrics = ['mae'])

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\dawin\OneDrive\Desktop\projects\ANN classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
## set up the tensorboard
log_dir = "regression_logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [21]:
## set up Early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [22]:
### train the model
history = model.fit(
    X_train,
    y_train,
    validation_data = (X_test, y_test),
    epochs = 100,
    callbacks = [early_stopping_callback, tensorflow_callback],

)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 100384.4453 - mae: 100384.4453 - val_loss: 98543.1562 - val_mae: 98543.1562
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99738.3047 - mae: 99738.3047 - val_loss: 97239.9844 - val_mae: 97239.9844
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 97469.0156 - mae: 97469.0156 - val_loss: 93887.6641 - val_mae: 93887.6641
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92945.7734 - mae: 92945.7734 - val_loss: 88206.5938 - val_mae: 88206.5938
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 86205.5781 - mae: 86205.5781 - val_loss: 80630.0000 - val_mae: 80630.0000
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 77942.8828 - mae: 77942.8828 - val_loss: 72271.9688 - val_mae: 72271.9688
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 69419.4375 - mae: 69419.4375 - val_loss: 64398.6172 - val_mae: 64398.6172
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 61915.5039 - mae: 61915.5039 - val_loss: 58246.0117 - val_mae: 58246.0117
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 56400.2227 - mae: 56400.2227 - val_loss: 54071.0625 - val_mae: 54071.0625
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 52997.4883 - mae: 52997.4883 - val_loss: 51909.4219 - val_mae: 51909.4219
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51294.8047 - mae: 51294.8047 - val_loss: 51077.6055 - val_mae: 51077.6055
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50596.6719 - mae: 50596.6719 - val_loss: 50821.8047 - val_mae: 50821.8047
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50345.3359 - mae: 50345.3359 - val_loss: 50742.0508 - val_mae: 50742.0508
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50225.8594 - mae: 50225.8594 - val_loss: 50694.4453 - val_mae: 50694.4453
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50156.6445 - mae: 50156.6445 - val_loss: 50662.2344 - val_mae: 50662.2344
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50103.7031 - mae: 50103.7031 - val_loss: 50633.5938 - val_mae: 50633.5938
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50060.5430 - mae: 50060.5430 - val_loss: 50598.9805 - val_mae: 50598.9805
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50017.6719 - mae: 50017.6719 - val_loss: 50571.5508 - val_mae: 50571.5508
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49983.8594 - mae: 49983.8594 - val_loss: 50537.2812 - val_mae: 50537.2812
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49950.2070 - mae: 49950.2070 - val_loss: 50517.6211 - val_mae: 50517.6211
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49922.8359 - mae: 49922.8359 - val_loss: 50493.7148 - val_mae: 50493.7148
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49892.6953 - mae: 49892.6953 - val_loss: 50466.9336 - val_mae: 50466.9336
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49867.3477 - mae: 49867.3477 - val_loss: 50458.8047 - val_mae: 50458.8047
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49843.9492 - mae: 49843.9492 - val_loss: 50446.6289 - val_mae: 50446.6289
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49821.9297 - mae: 49821.9297 - val_loss: 50434.0391 - val_mae: 50434.0391
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49800.5625 - mae: 49800.5625 - val_loss: 50423.7617 - val_mae: 50423.7617
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49780.7227 - mae: 49780.7227 - val_loss: 50410.0938 - val_mae: 50410.0938
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49761.7383 - mae: 49761.7383 - val_loss: 50412.1914 - val_mae: 50412.1914
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49744.3789 - mae: 49744.3789 - val_loss: 50401.4922 - val_mae: 50401.4922
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49729.4883 - mae: 49729.4883 - val_loss: 50400.7539 - val_mae: 50400.7539
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49713.1562 - mae: 49713.1562 - val_loss: 50395.1602 - val_mae: 50395.1602
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49699.5977 - mae: 49699.5977 - val_loss: 50385.9570 - val_mae: 50385.9570
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49682.6367 - mae: 49682.6367 - val_loss: 50390.7695 - val_mae: 50390.7695
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49668.5312 - mae: 49668.5312 - val_loss: 50398.2891 - val_mae: 50398.2891
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49657.3047 - mae: 49657.3047 - val_loss: 50388.8086 - val_mae: 50388.8086
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49648.0234 - mae: 49648.0234 - val_loss: 50387.8828 - val_mae: 50387.8828
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49633.5078 - mae: 49633.5078 - val_loss: 50373.8008 - val_mae: 50373.8008
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49622.7773 - mae: 49622.7773 - val_loss: 50369.2773 - val_mae: 50369.2773
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49608.8477 - mae: 49608.8477 - val_loss: 50372.1016 - val_mae: 50372.1016
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49596.4844 - mae: 49596.4844 - val_loss: 50367.8594 - val_mae: 50367.8594
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49585.5977 - mae: 49585.5977 - val_loss: 50378.8281 - val_mae: 50378.8281
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49579.5586 - mae: 49579.5586 - val_loss: 50378.1055 - val_mae: 50378.1055
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49569.1641 - mae: 49569.1641 - val_loss: 50392.7539 - val_mae: 50392.7539
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49559.9727 - mae: 49559.9727 - val_loss: 50374.4258 - val_mae: 50374.4258
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49549.5234 - mae: 49549.5234 - val_loss: 50371.4375 - val_mae: 50371.4375
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49541.7227 - mae: 49541.7227 - val_loss: 50363.5156 - val_mae: 50363.5156
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49532.5508 - mae: 49532.5508 - val_loss: 50379.5117 - val_mae: 50379.5117
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49523.0273 - mae: 49523.0273 - val_loss: 50374.4883 - val_mae: 50374.4883
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49518.7969 - mae: 49518.7969 - val_loss: 50381.5352 - val_mae: 50381.5352
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49509.3359 - mae: 49509.3359 - val_loss: 50383.3828 - val_mae: 50383.3828
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49501.6719 - mae: 49501.6719 - val_loss: 50384.8516 - val_mae: 50384.8516
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49498.6406 - mae: 49498.6406 - val_loss: 50377.0625 - val_mae: 50377.0625
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49490.2578 - mae: 49490.2578 - val_loss: 50381.6758 - val_mae: 50381.6758
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49482.3633 - mae: 49482.3633 - val_loss: 50385.0625 - val_mae: 50385.0625
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49479.1133 - mae: 49479.1133 - val_loss: 50376.4805 - val_mae: 50376.4805
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49468.5625 - mae: 49468.5625 - val_loss: 50385.7266 - val_mae: 50385.7266

In [29]:
## Load Tensorboard Extension
%load_ext tensorboard

In [30]:
%tensorboard --logdir regression_logs/fit

In [31]:
## Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print('Test loss:', test_loss)
print('Test mae:', test_mae)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50363.5156 - mae: 50363.5156
Test loss: 50363.515625
Test mae: 50363.515625

In [32]:
model.save('Regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.